# Generated by Django 4.2.9 on 2024-01-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_interface', '0003_pending_order_item_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
