# Generated by Django 4.2.9 on 2024-01-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_interface', '0004_alter_item_item_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='restraunt_rating_value',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
