# Generated by Django 4.2.9 on 2025-12-02 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_interface', '0005_alter_item_item_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restraunt',
            name='of_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='seller_interface.seller_profile'),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='restraunt_rating_value',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
    ]
