# Generated by Django 4.2.9 on 2024-01-30 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_interface', '0002_pending_order_order_to_alter_restraunt_of_seller'),
        ('user_interface', '0002_user_profile_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='of_restraunt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller_interface.restraunt'),
            preserve_default=False,
        ),
    ]
