# Generated by Django 4.2.9 on 2025-12-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0003_basket_of_restraunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_branch',
            field=models.CharField(choices=[('A7', 'CS'), ('AA', 'ECE'), ('A8', 'ENI'), ('A3', 'EEE'), ('A4', 'MECH'), ('AB', 'MANU'), ('A2', 'CIVIL'), ('A1', 'CHEMICAL'), ('B5', 'Msc. PHY'), ('B1', 'Msc. BIO'), ('B2', 'Msc. CHEM'), ('A5', 'PHARMA'), ('B4', 'Msc. MATH'), ('B3', 'Msc. ECO'), ('B3', 'Msc. ECO')], default='A7', max_length=20),
        ),
    ]
